#!/usr/bin/env bash
# Scan currently-running agent CLI processes (claude, codex, agy) and write
# a snapshot of resumable sessions to disk. Read by agent-sessions-restore.sh.
#
# Triggers:
#   - bash EXIT trap (in shell rc)
#   - launchd periodic (every 5 min)
#   - manual: just run this script
#
# Snapshot is atomic: write to tmpfile, fsync, rename. Prior snapshot
# preserved as snapshot.prev so a buggy scan can't erase known-good state.

set -u

STATE_DIR="$HOME/.local/state/agent-sessions"
SNAPSHOT="$STATE_DIR/snapshot"
TMPFILE="$STATE_DIR/snapshot.tmp.$$"

mkdir -p "$STATE_DIR"

# Exclude any process whose ancestor chain includes our own PID. Prevents a
# logging-out shell from snapshotting its own dying claude as "live".
SELF_PID=$$
is_ancestor() {
  local pid=$1
  while [ "$pid" -gt 1 ]; do
    [ "$pid" = "$SELF_PID" ] && return 0
    pid=$(ps -o ppid= -p "$pid" 2>/dev/null | tr -d ' ')
    [ -z "$pid" ] && return 1
  done
  return 1
}

# Resolve PID -> cwd via lsof. Returns empty string on failure.
pid_cwd() {
  lsof -a -d cwd -p "$1" -Fn 2>/dev/null | awk '/^n/ {print substr($0,2); exit}'
}

# Sanitize: lowercase, replace non-alnum with dash, trim.
slug() {
  printf '%s' "$1" \
    | tr '[:upper:]' '[:lower:]' \
    | sed 's/[^a-z0-9]/-/g; s/^-*//; s/-*$//; s/--*/-/g' \
    | cut -c1-24
}

declare -a entries=()
seen_uuids=" "

# claude --resume <uuid>: the primary resumable form.
# Using `ps -axo` directly rather than pgrep — macOS pgrep silently skips
# some claude PIDs (observed: missed the user's interactive parent claude
# when snapshot ran from inside its child bash).
list_pids_named() {
  ps -axo pid,comm 2>/dev/null | awk -v n="$1" '$2==n {print $1}'
}

for pid in $(list_pids_named claude); do
  is_ancestor "$pid" && continue
  cmd=$(ps -o command= -p "$pid" 2>/dev/null)
  case "$cmd" in
    *--resume*) ;;
    *) continue ;;
  esac
  # Skip --fork-session (subagent, not standalone-restorable)
  case "$cmd" in *--fork-session*) continue ;; esac
  uuid=$(printf '%s' "$cmd" | grep -oE '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' | head -1)
  [ -z "$uuid" ] && continue
  # Dedup: claude spawns multiple PIDs sharing the same session UUID
  case "$seen_uuids" in *" $uuid "*) continue ;; esac
  seen_uuids+="$uuid "
  cwd=$(pid_cwd "$pid")
  [ -z "$cwd" ] && continue
  flags=""
  case "$cmd" in *--dangerously-skip-permissions*) flags="--dangerously-skip-permissions " ;; esac
  name=$(slug "$(basename "$cwd")")
  [ -z "$name" ] && name="session"
  entries+=("$name|$cwd|claude ${flags}--resume $uuid")
done

# Bare claude (no --resume): can't restore a specific session, but at
# least open claude in the right cwd so the user can /resume from menu.
seen_cwds=" "
for entry in "${entries[@]}"; do
  cwd_part=$(printf '%s' "$entry" | cut -d'|' -f2)
  seen_cwds+="$cwd_part "
done
for pid in $(list_pids_named claude); do
  is_ancestor "$pid" && continue
  cmd=$(ps -o command= -p "$pid" 2>/dev/null)
  case "$cmd" in *--resume*|*--fork-session*|*daemon*|*--bg-*) continue ;; esac
  cwd=$(pid_cwd "$pid")
  [ -z "$cwd" ] && continue
  # Skip if we already captured a resumable session for this cwd
  case "$seen_cwds" in *" $cwd "*) continue ;; esac
  seen_cwds+="$cwd "
  flags=""
  case "$cmd" in *--dangerously-skip-permissions*) flags=" --dangerously-skip-permissions" ;; esac
  name=$(slug "$(basename "$cwd")")
  [ -z "$name" ] && name="session"
  entries+=("$name|$cwd|claude${flags}")
done

# agy --conversation <id>: antigravity's resume form
for pid in $(list_pids_named agy); do
  is_ancestor "$pid" && continue
  cmd=$(ps -o command= -p "$pid" 2>/dev/null)
  case "$cmd" in
    *--conversation*) ;;
    *) continue ;;
  esac
  conv=$(printf '%s' "$cmd" | awk '{for(i=1;i<=NF;i++) if($i=="--conversation") print $(i+1)}' | head -1)
  [ -z "$conv" ] && continue
  cwd=$(pid_cwd "$pid")
  [ -z "$cwd" ] && continue
  name=$(slug "agy-$(basename "$cwd")")
  entries+=("$name|$cwd|agy --conversation $conv")
done

# codex sessions are one-shot exec invocations and have no resume; skipping.

# Write snapshot atomically. Preserve prior as snapshot.prev.
timestamp=$(date -u +%Y-%m-%dT%H:%M:%SZ)
{
  printf '# Auto-generated by agent-sessions-snapshot.sh at %s\n' "$timestamp"
  printf '# Sessions captured: %d\n' "${#entries[@]}"
  printf 'SNAPSHOT_AT=%q\n' "$timestamp"
  printf 'SESSIONS=(\n'
  for e in "${entries[@]}"; do
    printf '  %q\n' "$e"
  done
  printf ')\n'
} > "$TMPFILE"

if [ -f "$SNAPSHOT" ]; then
  cp -f "$SNAPSHOT" "$SNAPSHOT.prev"
fi
mv -f "$TMPFILE" "$SNAPSHOT"
