# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/79e1c003-46c6-400b-b7b8-6650c633e83f";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."crypted".device = "/dev/disk/by-uuid/806af537-855c-4e61-aa0a-87e0c08df2da";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4A70-51E8";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # Check and repair boot partition health before activation
  system.activationScripts.check-boot-health = lib.stringAfter [ "specialfs" ] ''
    echo "Checking /boot filesystem health..."
    BOOT_DEV=$(${pkgs.util-linux}/bin/findmnt -n -o SOURCE /boot)
    if ${pkgs.dosfstools}/bin/fsck.vfat -n "$BOOT_DEV" 2>&1 | grep -q "Dirty bit\|differences between boot sector"; then
      echo "WARNING: /boot filesystem has issues. Attempting repair..."
      ${pkgs.dosfstools}/bin/fsck.vfat -a "$BOOT_DEV" || true
      ${pkgs.dosfstools}/bin/fsck.vfat -a -b "$BOOT_DEV" || true
      echo "Boot filesystem repaired."
    else
      echo "/boot filesystem is healthy."
    fi
  '';

  swapDevices = [
    { device = "/swapfile"; size = 10240; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}